# Generated by Django 3.2.16 on 2023-01-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_challenge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
