# Generated by Django 3.2.16 on 2022-12-07 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_challenge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Challenges',
            new_name='Challenge',
        ),
    ]
