# Generated by Django 3.2.16 on 2023-01-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_challenge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='challenge',
        ),
    ]
