# Generated by Django 3.2.16 on 2023-01-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_challenge', '0002_auto_20230104_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
