# Generated by Django 3.2.16 on 2023-01-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_challenge', '0002_remove_post_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='challenge',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='drawing_challenge.challenge'),
            preserve_default=False,
        ),
    ]
