# Generated by Django 3.2.16 on 2023-01-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_challenge', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='challenge',
        ),
    ]
