# Generated by Django 3.2.16 on 2023-01-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_challenge', '0008_auto_20230113_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
