# Generated by Django 3.2.16 on 2023-01-18 10:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing_challenge', '0009_alter_challenge_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='challenge_prompt'),
            preserve_default=False,
        ),
    ]
